import "../styles/html-result.css"
import "katex/dist/katex.min.css"
import "katex/dist/contrib/copy-tex"
import { ReaderLayout } from "../components/ReaderLayout"
import { useDocumentContext } from "@/context/DocumentContext"
import { useTTS } from "@/context/TTSContext"
import { useTTSChunkDetection } from "@/hooks/use-tts-chunk-detection"

interface Props {
  content: string
  imagesReady: boolean
  onDownload: () => void
  onReset: () => void
}

export function HtmlResultPage({
  content,
  imagesReady,
  onDownload,
  onReset,
}: Props) {
  const documentContext = useDocumentContext()
  const chunks = documentContext?.chunks ?? []
  const { isEnabled } = useTTS()
  const { handleContentClick } = useTTSChunkDetection(chunks)

  return (
    <ReaderLayout
      onDownload={onDownload}
      onReset={onReset}
      showThemeToggle
      showSidebar
      downloadDisabled={!imagesReady}
    >
      {/* Safe: content is generated by Marker from user's own uploaded document */}
      <div
        onClick={isEnabled ? handleContentClick : undefined}
        style={isEnabled ? { cursor: "pointer" } : undefined}
        dangerouslySetInnerHTML={{ __html: content }}
      />
    </ReaderLayout>
  )
}
