import "../styles/html-result.css"
import "katex/dist/katex.min.css"
import "katex/dist/contrib/copy-tex"
import { ReaderLayout } from "../components/ReaderLayout"

interface Props {
  content: string
  imagesReady: boolean
  documentId: string | null
  markdown: string
  onDownload: () => void
  onReset: () => void
}

export function HtmlResultPage({
  content,
  imagesReady,
  documentId,
  markdown,
  onDownload,
  onReset,
}: Props) {
  return (
    <ReaderLayout
      onDownload={onDownload}
      onReset={onReset}
      showThemeToggle
      showAIChat
      downloadDisabled={!imagesReady}
      documentId={documentId}
      markdown={markdown}
    >
      {/* Safe: content is generated by Marker from user's own uploaded document */}
      <div dangerouslySetInnerHTML={{ __html: content }} />
    </ReaderLayout>
  )
}
