import "../styles/html-result.css"
import "katex/dist/katex.min.css"
import "katex/dist/contrib/copy-tex"
import type { ChunkBlock } from "../hooks/use-conversion"
import { ReaderLayout } from "../components/ReaderLayout"

interface Props {
  content: string
  imagesReady: boolean
  chunks: ChunkBlock[]
  markdown: string
  filename: string
  onDownload: () => void
  onReset: () => void
}

export function HtmlResultPage({
  content,
  imagesReady,
  chunks,
  markdown,
  filename,
  onDownload,
  onReset,
}: Props) {
  return (
    <ReaderLayout
      onDownload={onDownload}
      onReset={onReset}
      showThemeToggle
      showAIChat
      downloadDisabled={!imagesReady}
      chunks={chunks}
      markdown={markdown}
      filename={filename}
    >
      {/* Safe: content is generated by Marker from user's own uploaded document */}
      <div dangerouslySetInnerHTML={{ __html: content }} />
    </ReaderLayout>
  )
}
